# tip poartă
GATE_TYPE = "swing_double"

# dimensiuni poartă
GATE_WIDTH = 4000.0
GATE_HEIGHT = 1800.0
GAP = 20.0

# profil
PROFILE_SIZE = 40.0
PROFILE_THICKNESS = 2.0

# NUMĂR BARE VERTICALE (inclusiv cadrul)
VERTICAL_COUNT = 6

# NUMĂR BARE ORIZONTALE
HORIZONTAL_COUNT = 0
